#!/bin/sh

BUILD_FOLDER=cmake-build-debug

echo "---- Creating build folder: ./${BUILD_FOLDER}..."
mkdir -p $BUILD_FOLDER


echo "---- Have CMake build initial folders..."
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug --build $BUILD_FOLDER .

echo "---- Finalize CMake build after conan update"
cmake --build $BUILD_FOLDER
