#!/bin/sh

conan remote update bincrafters https://api.bintray.com/conan/bincrafters/public-conan

conan install spirit-sensor-gateway -s build_type=Debug --install-folder=cmake-build-debug --build missing
